namespace Mostlylucid.BotDetection.UI.Models;

/// <summary>
///     Real-time detection event for dashboard display.
///     Sent via SignalR when a new detection occurs.
/// </summary>
public sealed record DashboardDetectionEvent
{
    public required string RequestId { get; init; }
    public required DateTime Timestamp { get; init; }
    public required bool IsBot { get; init; }
    public required double BotProbability { get; init; }
    public required double Confidence { get; init; }
    public required string RiskBand { get; init; }
    public string? BotType { get; init; }
    public string? BotName { get; init; }
    public string? Action { get; init; }
    public string? PolicyName { get; init; }
    public required string Method { get; init; }
    public required string Path { get; init; }
    public int StatusCode { get; init; }
    public double ProcessingTimeMs { get; init; }
    public string? IpAddress { get; init; }
    public string? UserAgent { get; init; }
    public List<string> TopReasons { get; init; } = new();
    public string? PrimarySignature { get; init; }

    /// <summary>
    ///     ISO 3166-1 alpha-2 country code from geo enrichment (e.g., "US", "DE", "CN").
    /// </summary>
    public string? CountryCode { get; init; }

    /// <summary>
    ///     Plain-english description generated by Ollama LLM (async, may arrive later via SignalR update).
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    ///     Marketing-friendly narrative built server-side from detection data (instant, every request).
    ///     Examples: "Scraper from datacenter IP - caught by TLS fingerprint mismatch"
    ///              "Real Chrome 134 user from Glasgow - verified by browser fingerprint"
    /// </summary>
    public string? Narrative { get; init; }

    /// <summary>
    ///     Per-detector contributions for drill-down display.
    ///     Key: detector name, Value: contribution details.
    /// </summary>
    public Dictionary<string, DashboardDetectorContribution>? DetectorContributions { get; init; }

    /// <summary>
    ///     Non-PII signals from the blackboard for debugging.
    /// </summary>
    public Dictionary<string, object>? ImportantSignals { get; init; }

    public double? ThreatScore { get; init; }
    public string? ThreatBand { get; init; }

    // Sparkline history removed from SignalR broadcasts to reduce payload bloat.
    // Clients fetch sparkline data on-demand via the dashboard API endpoints.
}

/// <summary>
///     Lightweight detector contribution for dashboard display.
/// </summary>
public sealed record DashboardDetectorContribution
{
    public required double ConfidenceDelta { get; init; }
    public required double Contribution { get; init; }
    public string? Reason { get; init; }
    public double ExecutionTimeMs { get; init; }
    public int Priority { get; init; }
}

/// <summary>
///     Signature observation for the scrolling feed.
///     Shows unique signatures being seen in real-time.
/// </summary>
public sealed record DashboardSignatureEvent
{
    public required string SignatureId { get; init; }
    public required DateTime Timestamp { get; init; }
    public required string PrimarySignature { get; init; }
    public string? IpSignature { get; init; }
    public string? UaSignature { get; init; }
    public string? ClientSideSignature { get; init; }
    public int FactorCount { get; init; }
    public required string RiskBand { get; init; }
    public int HitCount { get; init; }
    public bool IsKnownBot { get; init; }
    public string? BotName { get; init; }
    public double? BotProbability { get; init; }
    public double? Confidence { get; init; }
    public double? ProcessingTimeMs { get; init; }
    public string? BotType { get; init; }
    public string? Action { get; init; }
    public string? LastPath { get; init; }
    public string? Narrative { get; init; }
    public string? Description { get; init; }
    public List<string>? TopReasons { get; init; }
    public double? ThreatScore { get; init; }
    public string? ThreatBand { get; init; }
}

/// <summary>
///     Summary statistics for dashboard overview.
///     Updated periodically and sent to clients.
/// </summary>
public sealed record DashboardSummary
{
    public required DateTime Timestamp { get; init; }
    public required int TotalRequests { get; init; }
    public required int BotRequests { get; init; }
    public required int HumanRequests { get; init; }
    public required int UncertainRequests { get; init; }

    public double BotPercentage => TotalRequests > 0
        ? (double)BotRequests / TotalRequests * 100
        : 0;

    public required Dictionary<string, int> RiskBandCounts { get; init; }
    public required Dictionary<string, int> TopBotTypes { get; init; }
    public required Dictionary<string, int> TopActions { get; init; }
    public double AverageProcessingTimeMs { get; init; }
    public double LastProcessingTimeMs { get; init; }
    public required int UniqueSignatures { get; init; }
}

/// <summary>
///     Time-series data point for charts.
/// </summary>
public sealed record DashboardTimeSeriesPoint
{
    public required DateTime Timestamp { get; init; }
    public required int BotCount { get; init; }
    public required int HumanCount { get; init; }
    public required int TotalCount { get; init; }
    public Dictionary<string, int>? RiskBandCounts { get; init; }
}

/// <summary>
///     Filter criteria for dashboard queries.
/// </summary>
public sealed record DashboardFilter
{
    public DateTime? StartTime { get; init; }
    public DateTime? EndTime { get; init; }
    public List<string>? RiskBands { get; init; }
    public bool? IsBot { get; init; }
    public string? PathContains { get; init; }
    public string? SignatureId { get; init; }
    public bool HighRiskOnly { get; init; }
    public int? Limit { get; init; } = 100;
    public int? Offset { get; init; } = 0;
}

/// <summary>
///     User agent family summary for the UA tab.
/// </summary>
public sealed record DashboardUserAgentSummary
{
    public required string Family { get; init; }
    public required string Category { get; init; }
    public required int TotalCount { get; init; }
    public required int BotCount { get; init; }
    public required int HumanCount { get; init; }
    public required double BotRate { get; init; }
    public required Dictionary<string, int> Versions { get; init; }
    public required Dictionary<string, int> Countries { get; init; }
    public required double AvgConfidence { get; init; }
    public required double AvgProcessingTimeMs { get; init; }
    public required DateTime LastSeen { get; init; }
}

/// <summary>
///     Cluster summary for dashboard display.
///     Broadcast when clusters are updated (before LLM descriptions arrive).
/// </summary>
public sealed record DashboardClusterEvent
{
    public required string ClusterId { get; init; }
    public required string Label { get; init; }
    public string? Description { get; init; }
    public required string Type { get; init; }
    public required int MemberCount { get; init; }
    public required double AvgBotProb { get; init; }
    public string? Country { get; init; }
    public double AverageSimilarity { get; init; }
    public double TemporalDensity { get; init; }
    public string? DominantIntent { get; init; }
    public double AverageThreatScore { get; init; }
}