namespace Mostlylucid.BotDetection.UI.Models;

/// <summary>
///     Real-time detection event for dashboard display.
///     Sent via SignalR when a new detection occurs.
/// </summary>
public sealed record DashboardDetectionEvent
{
    public required string RequestId { get; init; }
    public required DateTime Timestamp { get; init; }
    public required bool IsBot { get; init; }
    public required double BotProbability { get; init; }
    public required double Confidence { get; init; }
    public required string RiskBand { get; init; }
    public string? BotType { get; init; }
    public string? BotName { get; init; }
    public string? Action { get; init; }
    public string? PolicyName { get; init; }
    public required string Method { get; init; }
    public required string Path { get; init; }
    // Settable (not init) so the broadcast middleware can stamp the FINAL downstream status
    // after _next without allocating a whole-record `with` copy per request. This is a
    // transient per-request DTO, not shared/cached state, so a mutable field is safe here.
    public int StatusCode { get; set; }

    /// <summary>
    ///     The real origin's HTTP status code, or <c>null</c> when this request never
    ///     reached the origin. Stamped post-_next alongside <see cref="StatusCode"/> from
    ///     <c>BotDetectionMiddleware.ResolveUpstreamStatusCode</c> (the gateway's
    ///     <c>UpstreamStatusTransform</c>). Null is the meaningful "honeypot / blocked /
    ///     throttled -- no real origin call" signal, not missing data: those responses are
    ///     synthesised by StyloBot's own enforcement gates before <c>MapReverseProxy</c>
    ///     ever runs.
    /// </summary>
    public int? UpstreamStatusCode { get; set; }

    public double ProcessingTimeMs { get; init; }
    /// <summary>Always null. Raw IPs are never persisted (zero-PII design). Present for interface compatibility only.</summary>
    public string? IpAddress { get; init; }
    public string? UserAgent { get; init; }
    public List<string> TopReasons { get; init; } = new();
    public string? PrimarySignature { get; init; }

    /// <summary>
    ///     Durable visitor handle resolved via <c>IDetectionArchive.ResolveEntityAsync</c>
    ///     against <c>entity_edges</c>. PrimarySignature can rotate as IP / UA shift;
    ///     the entity id is allocated once per actor and persists across rotations.
    ///     Drives the entity-keyed dashboard URL (<c>/dashboard/entity/{id}</c>) on
    ///     SbTopBots rows; falls back to the signature URL when null.
    /// </summary>
    public string? EntityId { get; init; }

    /// <summary>
    ///     ISO 3166-1 alpha-2 country code from geo enrichment (e.g., "US", "DE", "CN").
    /// </summary>
    public string? CountryCode { get; init; }

    /// <summary>
    ///     Plain-english description generated by Ollama LLM (async, may arrive later via SignalR update).
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    ///     Marketing-friendly narrative built server-side from detection data (instant, every request).
    ///     Examples: "Scraper from datacenter IP - caught by TLS fingerprint mismatch"
    ///              "Real Chrome 134 user from Glasgow - verified by browser fingerprint"
    /// </summary>
    public string? Narrative { get; init; }

    /// <summary>
    ///     Per-detector contributions for drill-down display.
    ///     Key: detector name, Value: contribution details.
    /// </summary>
    public Dictionary<string, DashboardDetectorContribution>? DetectorContributions { get; init; }

    /// <summary>
    ///     Non-PII signals from the blackboard for debugging.
    /// </summary>
    public Dictionary<string, object>? ImportantSignals { get; init; }

    public double? ThreatScore { get; init; }
    public string? ThreatBand { get; init; }
    public string? RiskJustification { get; init; }

    /// <summary>
    ///     True when <c>VerifiedBotContributor</c> confirmed the UA's bot claim
    ///     via the source signal <c>verifiedbot.confirmed=true</c> (operator IP
    ///     range or FCrDNS round-trip). Drives the green tick on the row's
    ///     verification badge once the value propagates into
    ///     <c>SignatureAggregate.IsVerifiedBot</c> and through the cache to
    ///     <c>DashboardTopBotEntry.IsVerifiedBot</c>.
    /// </summary>
    public bool IsVerifiedBot { get; init; }

    /// <summary>
    ///     PII-stripped raw User-Agent string for search and analytics.
    ///     Emails, credential URLs, and phone numbers are redacted before storage.
    /// </summary>
    public string? UserAgentRaw { get; init; }

    /// <summary>
    ///     eTLD+1 (registrable domain) resolved from the request Host header via
    ///     <c>DomainNormalizer</c> and cached in <c>HttpContext.Items</c> under
    ///     <c>HttpContextItemKeys.RequestScope</c>. Multi-domain partition key on
    ///     every analytics aggregate. Sourced from <c>RequestScope.Domain</c> at
    ///     write time; falls back to the <c>"unknown"</c> sentinel on the
    ///     <c>RequestScope.Unknown</c> path.
    /// </summary>
    public string? Domain { get; init; }

    /// <summary>
    ///     Full lowercased request Host header (with subdomain, no port). Sourced
    ///     from <c>RequestScope.Host</c> at write time; a single <c>Domain</c>
    ///     may fan out across many <c>Host</c> values (e.g. <c>auth.stylo.bot</c>
    ///     + <c>www.stylo.bot</c> both roll up to <c>Domain=stylo.bot</c>).
    ///     Falls back to the <c>"unknown"</c> sentinel on the
    ///     <c>RequestScope.Unknown</c> path.
    /// </summary>
    public string? Host { get; init; }

    /// <summary>
    ///     Raw Referer header value when the capture flag
    ///     AnalyticsCaptureOptions.IncludeReferer is enabled. Null otherwise.
    /// </summary>
    public string? Referer { get; init; }

    /// <summary>
    ///     Lowercased host extracted from Referer at write time
    ///     when AnalyticsCaptureOptions.DeriveReferrerHostAtWrite is enabled.
    ///     Persisted as the referrer_host column. Source of truth for the
    ///     Sources card's Referrers and Channels tabs.
    /// </summary>
    public string? ReferrerHost { get; init; }

    /// <summary>
    ///     Coarse device classification (Desktop / Mobile / Tablet) derived from
    ///     the UA family at write time when
    ///     AnalyticsCaptureOptions.DeriveDeviceClassAtWrite is enabled.
    ///     Persisted as the ua_device_class column. Null for bots and
    ///     unknown families.
    /// </summary>
    public string? UaDeviceClass { get; init; }

    /// <summary>
    ///     Response wire bytes from the Content-Length header. NULL for chunked / streamed
    ///     responses (Server-Sent Events, hub responses); rendered as "—" in UI.
    /// </summary>
    public long? ResponseBytes { get; init; }

    /// <summary>
    ///     16-dimensional radar shape vector for visual fingerprint display.
    ///     Derived from detector contributions and signal dimensions at detection time.
    /// </summary>
    public float[]? RadarShape { get; init; }

    // Sparkline history removed from SignalR broadcasts to reduce payload bloat.
    // Clients fetch sparkline data on-demand via the dashboard API endpoints.
}

/// <summary>
///     Lightweight detector contribution for dashboard display.
/// </summary>
public sealed record DashboardDetectorContribution
{
    public required double ConfidenceDelta { get; init; }
    public required double Contribution { get; init; }
    public string? Reason { get; init; }
    public double ExecutionTimeMs { get; init; }
    public int Priority { get; init; }
}

/// <summary>
///     Signature observation for the scrolling feed.
///     Shows unique signatures being seen in real-time.
/// </summary>
public sealed record DashboardSignatureEvent
{
    public required string SignatureId { get; init; }
    public required DateTime Timestamp { get; init; }
    public required string PrimarySignature { get; init; }
    public string? IpSignature { get; init; }
    public string? UaSignature { get; init; }
    public string? ClientSideSignature { get; init; }
    public int FactorCount { get; init; }
    public required string RiskBand { get; init; }
    public int HitCount { get; init; }
    public bool IsKnownBot { get; init; }
    public string? BotName { get; init; }
    public double? BotProbability { get; init; }
    public double? Confidence { get; init; }
    public double? ProcessingTimeMs { get; init; }
    public string? BotType { get; init; }
    public string? Action { get; init; }
    public string? LastPath { get; init; }
    public string? Narrative { get; init; }
    public string? Description { get; init; }
    public List<string>? TopReasons { get; init; }
    public double? ThreatScore { get; init; }
    public string? ThreatBand { get; init; }
    public string? RiskJustification { get; init; }
}

/// <summary>
///     Summary statistics for dashboard overview.
///     Updated periodically and sent to clients.
/// </summary>
public sealed record DashboardSummary
{
    public required DateTime Timestamp { get; init; }
    public required int TotalRequests { get; init; }
    public required int BotRequests { get; init; }
    public required int HumanRequests { get; init; }
    public required int UncertainRequests { get; init; }

    public double BotPercentage => TotalRequests > 0
        ? (double)BotRequests / TotalRequests * 100
        : 0;

    public required Dictionary<string, int> RiskBandCounts { get; init; }
    public required Dictionary<string, int> TopBotTypes { get; init; }
    public required Dictionary<string, int> TopActions { get; init; }
    public double AverageProcessingTimeMs { get; init; }
    public double LastProcessingTimeMs { get; init; }
    public required int UniqueSignatures { get; init; }

    // Fingerprint-level counts derived from the signatures table (one row per
    // unique fingerprint, with EWMA-blended bot_probability + risk_band).
    // Distinct from BotRequests/HumanRequests which count individual detection rows.
    // Dashboards should prefer these for "how many actors did we see" displays;
    // BotRequests/HumanRequests are still correct for "how much traffic" displays.
    public int BotFingerprints { get; init; }
    public int HumanFingerprints { get; init; }
    public int HighRiskFingerprints { get; init; }

    // Traffic volume and latency aggregates — computed from the detections sub-query
    // and therefore subject to the same audience filter (when set).
    public long BytesOut { get; init; }
    // SQLite lacks PERCENTILE_CONT — approximation: avg + (max - avg) * 0.9.
    // Postgres backend returns true PERCENTILE_CONT.
    public double P95ProcessingTimeMs { get; init; }
    public double MaxProcessingTimeMs { get; init; }
}

/// <summary>
///     Time-series data point for charts.
/// </summary>
public sealed record DashboardTimeSeriesPoint
{
    public required DateTime Timestamp { get; init; }
    public required int BotCount { get; init; }
    public required int HumanCount { get; init; }
    public required int TotalCount { get; init; }
    public Dictionary<string, int>? RiskBandCounts { get; init; }
    public long BytesOut { get; init; }
    public double AvgProcessingTimeMs { get; init; }
    // SQLite lacks PERCENTILE_CONT — approximation: avg + (max - avg) * 0.9.
    // Postgres backend returns true PERCENTILE_CONT.
    public double P95ProcessingTimeMs { get; init; }
    public double MaxProcessingTimeMs { get; init; }
}

/// <summary>
///     Filter criteria for dashboard queries.
/// </summary>
public sealed record DashboardFilter
{
    public DateTime? StartTime { get; init; }
    public DateTime? EndTime { get; init; }
    public List<string>? RiskBands { get; init; }
    public bool? IsBot { get; init; }
    public string? PathContains { get; init; }
    public string? SignatureId { get; init; }
    public bool HighRiskOnly { get; init; }
    public int? Limit { get; init; } = 100;
    public int? Offset { get; init; } = 0;
}

/// <summary>
///     User agent family summary for the UA tab.
/// </summary>
public sealed record DashboardUserAgentSummary
{
    public required string Family { get; init; }
    public required string Category { get; init; }
    public required int TotalCount { get; init; }
    public required int BotCount { get; init; }
    public required int HumanCount { get; init; }
    public required double BotRate { get; init; }
    public required Dictionary<string, int> Versions { get; init; }
    public required Dictionary<string, int> Countries { get; init; }
    public required double AvgConfidence { get; init; }
    public required double AvgProcessingTimeMs { get; init; }
    public required DateTime LastSeen { get; init; }
    /// <summary>Total bytes sent in responses for requests attributed to this UA family.</summary>
    public long BytesOut { get; init; }
    /// <summary>
    ///     P95 processing-time approximation: avg + 90% of (max - avg).
    ///     SQLite lacks PERCENTILE_CONT; the Postgres mirror in Task 10 replaces this with native p95.
    /// </summary>
    public double P95ProcessingTimeMs { get; init; }
}

/// <summary>
///     Cluster summary for dashboard display.
///     Broadcast when clusters are updated (before LLM descriptions arrive).
/// </summary>
public sealed record DashboardClusterEvent
{
    public required string ClusterId { get; init; }
    public required string Label { get; init; }
    public string? Description { get; init; }
    public required string Type { get; init; }
    public required int MemberCount { get; init; }
    public required double AvgBotProb { get; init; }
    public string? Country { get; init; }
    public double AverageSimilarity { get; init; }
    public double TemporalDensity { get; init; }
    public string? DominantIntent { get; init; }
    public double AverageThreatScore { get; init; }
}