using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Mostlylucid.BotDetection.Data.Sources;
using Mostlylucid.BotDetection.Extensions;

namespace Mostlylucid.BotDetection.Console.Services;

/// <summary>
///     Writes every external fetch source this binary declares — URL, purpose, licence,
///     cadence, failure mode, on-disk location — to a Markdown file, generated straight
///     from <see cref="IFetchSourceRegistry.GetDeclarations"/>. This is the "document
///     their URLs, use, etc." half of the dl- fetch-registry mission: the doc is always
///     regenerated from the same registry the admin UI and <c>/api/v1/fetch-sources</c>
///     read, never hand-typed — a hand-maintained list is exactly the second source of
///     truth this whole registry exists to prevent.
///     <para>
///     Trigger: <c>stylobot --output-fetch-sources-doc &lt;filename&gt;</c>. Runs before
///     the host starts, exits immediately after writing the file. Declarations only, not
///     live LastSuccessUtc/HealthState - those are runtime state and would go stale the
///     moment this file is committed; live status belongs in the admin UI / API, not a
///     static doc.
///     </para>
/// </summary>
public static class FetchSourceDocsCommand
{
    /// <summary>
    ///     Returns the path encoded in <c>--output-fetch-sources-doc</c>, or null when the
    ///     flag is absent (mirrors <see cref="ConfigOutputCommand.TryGetOutputPath"/>).
    /// </summary>
    public static string? TryGetOutputPath(string[] args)
    {
        for (var i = 0; i < args.Length - 1; i++)
        {
            if (args[i].Equals("--output-fetch-sources-doc", StringComparison.OrdinalIgnoreCase))
                return args[i + 1];
        }
        return null;
    }

    public static int WriteDoc(string outputPath, string[] args)
    {
        try
        {
            // Same source order WebApplicationBuilder would use, matching ConfigOutputCommand -
            // the declared sources (Enabled/Url) must reflect real config overrides, not just
            // YAML defaults, or the doc silently lies about a locally-configured deployment.
            var env = Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT")
                   ?? Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")
                   ?? "Production";
            var config = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: false)
                .AddJsonFile($"appsettings.{env}.json", optional: true, reloadOnChange: false)
                .AddEnvironmentVariables()
                .AddCommandLine(args)
                .Build();

            var services = new ServiceCollection();
            services.AddSingleton<IConfiguration>(config);
            services.AddBotDetection(config);
            using var provider = services.BuildServiceProvider();

            var registry = provider.GetRequiredService<IFetchSourceRegistry>();
            var declarations = registry.GetDeclarations()
                .OrderBy(d => d.Id, StringComparer.OrdinalIgnoreCase)
                .ToArray();

            var markdown = Render(declarations, env);

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(outputPath, markdown);

            System.Console.WriteLine($"  Wrote {declarations.Length} fetch sources to {outputPath}");
            System.Console.WriteLine($"  Environment: {env}");
            System.Console.WriteLine("  Declarations only (URL/purpose/licence/cadence) - live status is the admin UI / API's job, not this file.");
            return 0;
        }
        catch (Exception ex)
        {
            System.Console.Error.WriteLine($"  Failed to write fetch-sources doc: {ex.Message}");
            return 1;
        }
    }

    private static string Render(IReadOnlyList<FetchSourceDeclaration> declarations, string env)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# External Fetch Sources");
        sb.AppendLine();
        sb.AppendLine("Generated by `stylobot --output-fetch-sources-doc docs/fetch-sources.md`, straight from `IFetchSourceRegistry.GetDeclarations()`.");
        sb.AppendLine("Do not hand-edit — regenerate this file instead, or it drifts from what the binary actually does.");
        sb.AppendLine();
        sb.AppendLine($"Environment at generation time: `{env}`. Enabled/URL reflect config overrides present then, not just YAML defaults.");
        sb.AppendLine();
        sb.AppendLine($"{declarations.Count} declared sources, {declarations.Count(d => d.Enabled)} currently enabled.");
        sb.AppendLine();

        foreach (var d in declarations)
        {
            sb.AppendLine($"## {d.DisplayName} (`{d.Id}`)");
            sb.AppendLine();
            sb.AppendLine($"- **Enabled**: {(d.Enabled ? "yes" : "no")}");
            sb.AppendLine($"- **URL**: {(d.Url is null ? "_none_" : $"`{d.Url}`")}");
            sb.AppendLine($"- **Purpose**: {d.Purpose}");
            sb.AppendLine($"- **Licence**: {d.Licence ?? "_not specified_"}");
            sb.AppendLine($"- **Cadence**: {d.Cadence}");
            sb.AppendLine($"- **Failure mode**: {d.FailureMode}");
            sb.AppendLine($"- **On-disk location**: {d.OnDiskLocation ?? "_none_"}");
            sb.AppendLine($"- **Live status tracked**: {(d.HasLiveState ? "yes" : "no — see the next major version's per-source rollout")}");
            if (d.GroupedSourceIds is { Count: > 0 })
                sb.AppendLine($"- **Covers**: {string.Join(", ", d.GroupedSourceIds)} — this entry's timestamp is the only precision available for those sources today, not a per-source one.");
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
