// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: detection.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskBand int32

const (
	RiskBand_RISK_BAND_UNKNOWN   RiskBand = 0
	RiskBand_RISK_BAND_VERY_LOW  RiskBand = 1
	RiskBand_RISK_BAND_LOW       RiskBand = 2
	RiskBand_RISK_BAND_ELEVATED  RiskBand = 3
	RiskBand_RISK_BAND_MEDIUM    RiskBand = 4
	RiskBand_RISK_BAND_HIGH      RiskBand = 5
	RiskBand_RISK_BAND_VERY_HIGH RiskBand = 6
	RiskBand_RISK_BAND_VERIFIED  RiskBand = 7
)

// Enum value maps for RiskBand.
var (
	RiskBand_name = map[int32]string{
		0: "RISK_BAND_UNKNOWN",
		1: "RISK_BAND_VERY_LOW",
		2: "RISK_BAND_LOW",
		3: "RISK_BAND_ELEVATED",
		4: "RISK_BAND_MEDIUM",
		5: "RISK_BAND_HIGH",
		6: "RISK_BAND_VERY_HIGH",
		7: "RISK_BAND_VERIFIED",
	}
	RiskBand_value = map[string]int32{
		"RISK_BAND_UNKNOWN":   0,
		"RISK_BAND_VERY_LOW":  1,
		"RISK_BAND_LOW":       2,
		"RISK_BAND_ELEVATED":  3,
		"RISK_BAND_MEDIUM":    4,
		"RISK_BAND_HIGH":      5,
		"RISK_BAND_VERY_HIGH": 6,
		"RISK_BAND_VERIFIED":  7,
	}
)

func (x RiskBand) Enum() *RiskBand {
	p := new(RiskBand)
	*p = x
	return p
}

func (x RiskBand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskBand) Descriptor() protoreflect.EnumDescriptor {
	return file_detection_proto_enumTypes[0].Descriptor()
}

func (RiskBand) Type() protoreflect.EnumType {
	return &file_detection_proto_enumTypes[0]
}

func (x RiskBand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskBand.Descriptor instead.
func (RiskBand) EnumDescriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{0}
}

type RecommendedAction int32

const (
	RecommendedAction_RECOMMENDED_ACTION_ALLOW     RecommendedAction = 0
	RecommendedAction_RECOMMENDED_ACTION_THROTTLE  RecommendedAction = 1
	RecommendedAction_RECOMMENDED_ACTION_CHALLENGE RecommendedAction = 2
	RecommendedAction_RECOMMENDED_ACTION_BLOCK     RecommendedAction = 3
)

// Enum value maps for RecommendedAction.
var (
	RecommendedAction_name = map[int32]string{
		0: "RECOMMENDED_ACTION_ALLOW",
		1: "RECOMMENDED_ACTION_THROTTLE",
		2: "RECOMMENDED_ACTION_CHALLENGE",
		3: "RECOMMENDED_ACTION_BLOCK",
	}
	RecommendedAction_value = map[string]int32{
		"RECOMMENDED_ACTION_ALLOW":     0,
		"RECOMMENDED_ACTION_THROTTLE":  1,
		"RECOMMENDED_ACTION_CHALLENGE": 2,
		"RECOMMENDED_ACTION_BLOCK":     3,
	}
)

func (x RecommendedAction) Enum() *RecommendedAction {
	p := new(RecommendedAction)
	*p = x
	return p
}

func (x RecommendedAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommendedAction) Descriptor() protoreflect.EnumDescriptor {
	return file_detection_proto_enumTypes[1].Descriptor()
}

func (RecommendedAction) Type() protoreflect.EnumType {
	return &file_detection_proto_enumTypes[1]
}

func (x RecommendedAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommendedAction.Descriptor instead.
func (RecommendedAction) EnumDescriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{1}
}

type ThreatBand int32

const (
	ThreatBand_THREAT_BAND_NONE     ThreatBand = 0
	ThreatBand_THREAT_BAND_LOW      ThreatBand = 1
	ThreatBand_THREAT_BAND_ELEVATED ThreatBand = 2
	ThreatBand_THREAT_BAND_HIGH     ThreatBand = 3
	ThreatBand_THREAT_BAND_CRITICAL ThreatBand = 4
)

// Enum value maps for ThreatBand.
var (
	ThreatBand_name = map[int32]string{
		0: "THREAT_BAND_NONE",
		1: "THREAT_BAND_LOW",
		2: "THREAT_BAND_ELEVATED",
		3: "THREAT_BAND_HIGH",
		4: "THREAT_BAND_CRITICAL",
	}
	ThreatBand_value = map[string]int32{
		"THREAT_BAND_NONE":     0,
		"THREAT_BAND_LOW":      1,
		"THREAT_BAND_ELEVATED": 2,
		"THREAT_BAND_HIGH":     3,
		"THREAT_BAND_CRITICAL": 4,
	}
)

func (x ThreatBand) Enum() *ThreatBand {
	p := new(ThreatBand)
	*p = x
	return p
}

func (x ThreatBand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatBand) Descriptor() protoreflect.EnumDescriptor {
	return file_detection_proto_enumTypes[2].Descriptor()
}

func (ThreatBand) Type() protoreflect.EnumType {
	return &file_detection_proto_enumTypes[2]
}

func (x ThreatBand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatBand.Descriptor instead.
func (ThreatBand) EnumDescriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{2}
}

type DetectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemoteIp      string                 `protobuf:"bytes,4,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"` // "http" or "https", default "https"
	Tls           *TlsInfo               `protobuf:"bytes,6,opt,name=tls,proto3" json:"tls,omitempty"`           // optional; omit if not available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectRequest) Reset() {
	*x = DetectRequest{}
	mi := &file_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectRequest) ProtoMessage() {}

func (x *DetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectRequest.ProtoReflect.Descriptor instead.
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{0}
}

func (x *DetectRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *DetectRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DetectRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DetectRequest) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *DetectRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DetectRequest) GetTls() *TlsInfo {
	if x != nil {
		return x.Tls
	}
	return nil
}

type TlsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Cipher        string                 `protobuf:"bytes,2,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Ja3           string                 `protobuf:"bytes,3,opt,name=ja3,proto3" json:"ja3,omitempty"`
	Ja4           string                 `protobuf:"bytes,4,opt,name=ja4,proto3" json:"ja4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TlsInfo) Reset() {
	*x = TlsInfo{}
	mi := &file_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsInfo) ProtoMessage() {}

func (x *TlsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsInfo.ProtoReflect.Descriptor instead.
func (*TlsInfo) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{1}
}

func (x *TlsInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TlsInfo) GetCipher() string {
	if x != nil {
		return x.Cipher
	}
	return ""
}

func (x *TlsInfo) GetJa3() string {
	if x != nil {
		return x.Ja3
	}
	return ""
}

func (x *TlsInfo) GetJa4() string {
	if x != nil {
		return x.Ja4
	}
	return ""
}

type DetectResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsBot             bool                   `protobuf:"varint,1,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	BotProbability    float32                `protobuf:"fixed32,2,opt,name=bot_probability,json=botProbability,proto3" json:"bot_probability,omitempty"`
	Confidence        float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	BotType           string                 `protobuf:"bytes,4,opt,name=bot_type,json=botType,proto3" json:"bot_type,omitempty"` // empty string = no known type
	BotName           string                 `protobuf:"bytes,5,opt,name=bot_name,json=botName,proto3" json:"bot_name,omitempty"` // empty string = not identified
	RiskBand          RiskBand               `protobuf:"varint,6,opt,name=risk_band,json=riskBand,proto3,enum=stylobot.detection.v1.RiskBand" json:"risk_band,omitempty"`
	RecommendedAction RecommendedAction      `protobuf:"varint,7,opt,name=recommended_action,json=recommendedAction,proto3,enum=stylobot.detection.v1.RecommendedAction" json:"recommended_action,omitempty"`
	ThreatScore       float32                `protobuf:"fixed32,8,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	ThreatBand        ThreatBand             `protobuf:"varint,9,opt,name=threat_band,json=threatBand,proto3,enum=stylobot.detection.v1.ThreatBand" json:"threat_band,omitempty"`
	Reasons           []*Reason              `protobuf:"bytes,10,rep,name=reasons,proto3" json:"reasons,omitempty"`
	ProcessingTimeMs  float32                `protobuf:"fixed32,11,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	DetectorsRun      int32                  `protobuf:"varint,12,opt,name=detectors_run,json=detectorsRun,proto3" json:"detectors_run,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DetectResponse) Reset() {
	*x = DetectResponse{}
	mi := &file_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectResponse) ProtoMessage() {}

func (x *DetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectResponse.ProtoReflect.Descriptor instead.
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{2}
}

func (x *DetectResponse) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

func (x *DetectResponse) GetBotProbability() float32 {
	if x != nil {
		return x.BotProbability
	}
	return 0
}

func (x *DetectResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectResponse) GetBotType() string {
	if x != nil {
		return x.BotType
	}
	return ""
}

func (x *DetectResponse) GetBotName() string {
	if x != nil {
		return x.BotName
	}
	return ""
}

func (x *DetectResponse) GetRiskBand() RiskBand {
	if x != nil {
		return x.RiskBand
	}
	return RiskBand_RISK_BAND_UNKNOWN
}

func (x *DetectResponse) GetRecommendedAction() RecommendedAction {
	if x != nil {
		return x.RecommendedAction
	}
	return RecommendedAction_RECOMMENDED_ACTION_ALLOW
}

func (x *DetectResponse) GetThreatScore() float32 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

func (x *DetectResponse) GetThreatBand() ThreatBand {
	if x != nil {
		return x.ThreatBand
	}
	return ThreatBand_THREAT_BAND_NONE
}

func (x *DetectResponse) GetReasons() []*Reason {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *DetectResponse) GetProcessingTimeMs() float32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *DetectResponse) GetDetectorsRun() int32 {
	if x != nil {
		return x.DetectorsRun
	}
	return 0
}

type Reason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detector      string                 `protobuf:"bytes,1,opt,name=detector,proto3" json:"detector,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Impact        float32                `protobuf:"fixed32,3,opt,name=impact,proto3" json:"impact,omitempty"` // negative = bot signal, positive = human signal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reason) Reset() {
	*x = Reason{}
	mi := &file_detection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reason) ProtoMessage() {}

func (x *Reason) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reason.ProtoReflect.Descriptor instead.
func (*Reason) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{3}
}

func (x *Reason) GetDetector() string {
	if x != nil {
		return x.Detector
	}
	return ""
}

func (x *Reason) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Reason) GetImpact() float32 {
	if x != nil {
		return x.Impact
	}
	return 0
}

type DetectBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*DetectRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectBatchRequest) Reset() {
	*x = DetectBatchRequest{}
	mi := &file_detection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectBatchRequest) ProtoMessage() {}

func (x *DetectBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectBatchRequest.ProtoReflect.Descriptor instead.
func (*DetectBatchRequest) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{4}
}

func (x *DetectBatchRequest) GetRequests() []*DetectRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type DetectBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*DetectResponse      `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectBatchResponse) Reset() {
	*x = DetectBatchResponse{}
	mi := &file_detection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectBatchResponse) ProtoMessage() {}

func (x *DetectBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectBatchResponse.ProtoReflect.Descriptor instead.
func (*DetectBatchResponse) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{5}
}

func (x *DetectBatchResponse) GetResponses() []*DetectResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_detection_proto protoreflect.FileDescriptor

const file_detection_proto_rawDesc = "" +
	"\n" +
	"\x0fdetection.proto\x12\x15stylobot.detection.v1\"\xaf\x02\n" +
	"\rDetectRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12K\n" +
	"\aheaders\x18\x03 \x03(\v21.stylobot.detection.v1.DetectRequest.HeadersEntryR\aheaders\x12\x1b\n" +
	"\tremote_ip\x18\x04 \x01(\tR\bremoteIp\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x120\n" +
	"\x03tls\x18\x06 \x01(\v2\x1e.stylobot.detection.v1.TlsInfoR\x03tls\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\aTlsInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06cipher\x18\x02 \x01(\tR\x06cipher\x12\x10\n" +
	"\x03ja3\x18\x03 \x01(\tR\x03ja3\x12\x10\n" +
	"\x03ja4\x18\x04 \x01(\tR\x03ja4\"\xb0\x04\n" +
	"\x0eDetectResponse\x12\x15\n" +
	"\x06is_bot\x18\x01 \x01(\bR\x05isBot\x12'\n" +
	"\x0fbot_probability\x18\x02 \x01(\x02R\x0ebotProbability\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x19\n" +
	"\bbot_type\x18\x04 \x01(\tR\abotType\x12\x19\n" +
	"\bbot_name\x18\x05 \x01(\tR\abotName\x12<\n" +
	"\trisk_band\x18\x06 \x01(\x0e2\x1f.stylobot.detection.v1.RiskBandR\briskBand\x12W\n" +
	"\x12recommended_action\x18\a \x01(\x0e2(.stylobot.detection.v1.RecommendedActionR\x11recommendedAction\x12!\n" +
	"\fthreat_score\x18\b \x01(\x02R\vthreatScore\x12B\n" +
	"\vthreat_band\x18\t \x01(\x0e2!.stylobot.detection.v1.ThreatBandR\n" +
	"threatBand\x127\n" +
	"\areasons\x18\n" +
	" \x03(\v2\x1d.stylobot.detection.v1.ReasonR\areasons\x12,\n" +
	"\x12processing_time_ms\x18\v \x01(\x02R\x10processingTimeMs\x12#\n" +
	"\rdetectors_run\x18\f \x01(\x05R\fdetectorsRun\"T\n" +
	"\x06Reason\x12\x1a\n" +
	"\bdetector\x18\x01 \x01(\tR\bdetector\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x16\n" +
	"\x06impact\x18\x03 \x01(\x02R\x06impact\"V\n" +
	"\x12DetectBatchRequest\x12@\n" +
	"\brequests\x18\x01 \x03(\v2$.stylobot.detection.v1.DetectRequestR\brequests\"Z\n" +
	"\x13DetectBatchResponse\x12C\n" +
	"\tresponses\x18\x01 \x03(\v2%.stylobot.detection.v1.DetectResponseR\tresponses*\xbf\x01\n" +
	"\bRiskBand\x12\x15\n" +
	"\x11RISK_BAND_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12RISK_BAND_VERY_LOW\x10\x01\x12\x11\n" +
	"\rRISK_BAND_LOW\x10\x02\x12\x16\n" +
	"\x12RISK_BAND_ELEVATED\x10\x03\x12\x14\n" +
	"\x10RISK_BAND_MEDIUM\x10\x04\x12\x12\n" +
	"\x0eRISK_BAND_HIGH\x10\x05\x12\x17\n" +
	"\x13RISK_BAND_VERY_HIGH\x10\x06\x12\x16\n" +
	"\x12RISK_BAND_VERIFIED\x10\a*\x92\x01\n" +
	"\x11RecommendedAction\x12\x1c\n" +
	"\x18RECOMMENDED_ACTION_ALLOW\x10\x00\x12\x1f\n" +
	"\x1bRECOMMENDED_ACTION_THROTTLE\x10\x01\x12 \n" +
	"\x1cRECOMMENDED_ACTION_CHALLENGE\x10\x02\x12\x1c\n" +
	"\x18RECOMMENDED_ACTION_BLOCK\x10\x03*\x81\x01\n" +
	"\n" +
	"ThreatBand\x12\x14\n" +
	"\x10THREAT_BAND_NONE\x10\x00\x12\x13\n" +
	"\x0fTHREAT_BAND_LOW\x10\x01\x12\x18\n" +
	"\x14THREAT_BAND_ELEVATED\x10\x02\x12\x14\n" +
	"\x10THREAT_BAND_HIGH\x10\x03\x12\x18\n" +
	"\x14THREAT_BAND_CRITICAL\x10\x042\xcf\x01\n" +
	"\x10DetectionService\x12U\n" +
	"\x06Detect\x12$.stylobot.detection.v1.DetectRequest\x1a%.stylobot.detection.v1.DetectResponse\x12d\n" +
	"\vDetectBatch\x12).stylobot.detection.v1.DetectBatchRequest\x1a*.stylobot.detection.v1.DetectBatchResponseBHZ.github.com/scottgal/caddy-stylobot/proto;proto\xaa\x02\x15Stylobot.Detection.V1b\x06proto3"

var (
	file_detection_proto_rawDescOnce sync.Once
	file_detection_proto_rawDescData []byte
)

func file_detection_proto_rawDescGZIP() []byte {
	file_detection_proto_rawDescOnce.Do(func() {
		file_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_detection_proto_rawDesc), len(file_detection_proto_rawDesc)))
	})
	return file_detection_proto_rawDescData
}

var file_detection_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_detection_proto_goTypes = []any{
	(RiskBand)(0),               // 0: stylobot.detection.v1.RiskBand
	(RecommendedAction)(0),      // 1: stylobot.detection.v1.RecommendedAction
	(ThreatBand)(0),             // 2: stylobot.detection.v1.ThreatBand
	(*DetectRequest)(nil),       // 3: stylobot.detection.v1.DetectRequest
	(*TlsInfo)(nil),             // 4: stylobot.detection.v1.TlsInfo
	(*DetectResponse)(nil),      // 5: stylobot.detection.v1.DetectResponse
	(*Reason)(nil),              // 6: stylobot.detection.v1.Reason
	(*DetectBatchRequest)(nil),  // 7: stylobot.detection.v1.DetectBatchRequest
	(*DetectBatchResponse)(nil), // 8: stylobot.detection.v1.DetectBatchResponse
	nil,                         // 9: stylobot.detection.v1.DetectRequest.HeadersEntry
}
var file_detection_proto_depIdxs = []int32{
	9,  // 0: stylobot.detection.v1.DetectRequest.headers:type_name -> stylobot.detection.v1.DetectRequest.HeadersEntry
	4,  // 1: stylobot.detection.v1.DetectRequest.tls:type_name -> stylobot.detection.v1.TlsInfo
	0,  // 2: stylobot.detection.v1.DetectResponse.risk_band:type_name -> stylobot.detection.v1.RiskBand
	1,  // 3: stylobot.detection.v1.DetectResponse.recommended_action:type_name -> stylobot.detection.v1.RecommendedAction
	2,  // 4: stylobot.detection.v1.DetectResponse.threat_band:type_name -> stylobot.detection.v1.ThreatBand
	6,  // 5: stylobot.detection.v1.DetectResponse.reasons:type_name -> stylobot.detection.v1.Reason
	3,  // 6: stylobot.detection.v1.DetectBatchRequest.requests:type_name -> stylobot.detection.v1.DetectRequest
	5,  // 7: stylobot.detection.v1.DetectBatchResponse.responses:type_name -> stylobot.detection.v1.DetectResponse
	3,  // 8: stylobot.detection.v1.DetectionService.Detect:input_type -> stylobot.detection.v1.DetectRequest
	7,  // 9: stylobot.detection.v1.DetectionService.DetectBatch:input_type -> stylobot.detection.v1.DetectBatchRequest
	5,  // 10: stylobot.detection.v1.DetectionService.Detect:output_type -> stylobot.detection.v1.DetectResponse
	8,  // 11: stylobot.detection.v1.DetectionService.DetectBatch:output_type -> stylobot.detection.v1.DetectBatchResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_detection_proto_init() }
func file_detection_proto_init() {
	if File_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_detection_proto_rawDesc), len(file_detection_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_detection_proto_goTypes,
		DependencyIndexes: file_detection_proto_depIdxs,
		EnumInfos:         file_detection_proto_enumTypes,
		MessageInfos:      file_detection_proto_msgTypes,
	}.Build()
	File_detection_proto = out.File
	file_detection_proto_goTypes = nil
	file_detection_proto_depIdxs = nil
}
