// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: detection.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DetectionService_Detect_FullMethodName       = "/stylobot.detection.v1.DetectionService/Detect"
	DetectionService_DetectBatch_FullMethodName  = "/stylobot.detection.v1.DetectionService/DetectBatch"
	DetectionService_RenderWidget_FullMethodName = "/stylobot.detection.v1.DetectionService/RenderWidget"
)

// DetectionServiceClient is the client API for DetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetectionServiceClient interface {
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
	DetectBatch(ctx context.Context, in *DetectBatchRequest, opts ...grpc.CallOption) (*DetectBatchResponse, error)
	RenderWidget(ctx context.Context, in *RenderWidgetRequest, opts ...grpc.CallOption) (*RenderWidgetResponse, error)
}

type detectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectionServiceClient(cc grpc.ClientConnInterface) DetectionServiceClient {
	return &detectionServiceClient{cc}
}

func (c *detectionServiceClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, DetectionService_Detect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) DetectBatch(ctx context.Context, in *DetectBatchRequest, opts ...grpc.CallOption) (*DetectBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectBatchResponse)
	err := c.cc.Invoke(ctx, DetectionService_DetectBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) RenderWidget(ctx context.Context, in *RenderWidgetRequest, opts ...grpc.CallOption) (*RenderWidgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderWidgetResponse)
	err := c.cc.Invoke(ctx, DetectionService_RenderWidget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectionServiceServer is the server API for DetectionService service.
// All implementations must embed UnimplementedDetectionServiceServer
// for forward compatibility.
type DetectionServiceServer interface {
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
	DetectBatch(context.Context, *DetectBatchRequest) (*DetectBatchResponse, error)
	RenderWidget(context.Context, *RenderWidgetRequest) (*RenderWidgetResponse, error)
	mustEmbedUnimplementedDetectionServiceServer()
}

// UnimplementedDetectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectionServiceServer struct{}

func (UnimplementedDetectionServiceServer) Detect(context.Context, *DetectRequest) (*DetectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedDetectionServiceServer) DetectBatch(context.Context, *DetectBatchRequest) (*DetectBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectBatch not implemented")
}
func (UnimplementedDetectionServiceServer) RenderWidget(context.Context, *RenderWidgetRequest) (*RenderWidgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderWidget not implemented")
}
func (UnimplementedDetectionServiceServer) mustEmbedUnimplementedDetectionServiceServer() {}
func (UnimplementedDetectionServiceServer) testEmbeddedByValue()                          {}

// UnsafeDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectionServiceServer will
// result in compilation errors.
type UnsafeDetectionServiceServer interface {
	mustEmbedUnimplementedDetectionServiceServer()
}

func RegisterDetectionServiceServer(s grpc.ServiceRegistrar, srv DetectionServiceServer) {
	// If the following call panics, it indicates UnimplementedDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DetectionService_ServiceDesc, srv)
}

func _DetectionService_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_DetectBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).DetectBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_DetectBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).DetectBatch(ctx, req.(*DetectBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_RenderWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).RenderWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_RenderWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).RenderWidget(ctx, req.(*RenderWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DetectionService_ServiceDesc is the grpc.ServiceDesc for DetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stylobot.detection.v1.DetectionService",
	HandlerType: (*DetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _DetectionService_Detect_Handler,
		},
		{
			MethodName: "DetectBatch",
			Handler:    _DetectionService_DetectBatch_Handler,
		},
		{
			MethodName: "RenderWidget",
			Handler:    _DetectionService_RenderWidget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detection.proto",
}
