using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Moq;
using Mostlylucid.BotDetection.UI.TagHelpers.Dashboard;
using Xunit;

namespace Mostlylucid.BotDetection.Test.UI;

/// <summary>
///     Si2 (endpoint-IA unification), task 1: `&lt;sb-endpoints-list&gt;` is the tag-helper
///     entry point `_Endpoints.cshtml` uses for the canonical `/dashboard/site` control.
///     Before this change the tag helper forwarded sort/dir/page/pageSize/excludeStatic/
///     compact/contentOnly/heading/audience/range to the view component but silently
///     dropped path/method/threat/botPressure -- so a direct page load of
///     `/dashboard/site?method=POST` never actually filtered anything (only the OWN
///     hx-get links generated by an already-rendered list carried those params). This
///     proves the tag helper now forwards every URL-bound filter, including the new
///     mode/status pair, through to the view component invocation.
/// </summary>
public sealed class SbEndpointsListTagHelperForwardingTests
{
    [Fact]
    public async Task ProcessAsync_forwards_every_url_bound_filter_to_the_view_component()
    {
        object? captured = null;
        var vc = new Mock<IViewComponentHelper>();
        vc.Setup(v => v.InvokeAsync("SbEndpointsList", It.IsAny<object>()))
          .Callback<string, object>((_, args) => captured = args)
          .ReturnsAsync(new HtmlString(""));

        var helper = new SbEndpointsListTagHelper(vc.Object)
        {
            Path = "/api",
            Method = "POST",
            Mode = "api",
            Status = "5xx",
            Threat = "High",
            BotPressure = "high",
        };

        var context = new TagHelperContext(
            tagName: "sb-endpoints-list",
            allAttributes: new TagHelperAttributeList(),
            items: new Dictionary<object, object>(),
            uniqueId: "test");
        var output = new TagHelperOutput(
            "sb-endpoints-list",
            new TagHelperAttributeList(),
            (_, _) => Task.FromResult<TagHelperContent>(new DefaultTagHelperContent()));

        await helper.ProcessAsync(context, output);

        Assert.NotNull(captured);
        var type = captured!.GetType();
        Assert.Equal("/api", type.GetProperty("path")!.GetValue(captured));
        Assert.Equal("POST", type.GetProperty("method")!.GetValue(captured));
        Assert.Equal("api", type.GetProperty("mode")!.GetValue(captured));
        Assert.Equal("5xx", type.GetProperty("status")!.GetValue(captured));
        Assert.Equal("High", type.GetProperty("threat")!.GetValue(captured));
        Assert.Equal("high", type.GetProperty("botPressure")!.GetValue(captured));
    }
}
